# ===================================================
# application-dev.properties ? Overrides para DEV
# Se activa con: SPRING_PROFILES_ACTIVE=dev
# ===================================================

# DDL: Hibernate crea/modifica tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

app.migracion.backfill-estaciones.enabled=false

# JPA: mostrar SQL en desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.com.saasa=DEBUG

# Swagger activo en dev
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Logging nivel DEBUG en dev
#logging.level.com.{tugrupo}=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
